### ISSUE TITLE
Generate disconnect()

### ISSUE THREAD

**Issue by fcolon** [Eximchain/abi2lib#4]
As the library stands now, there is a `connect()` function which creates the connection to the network, but there is never a `disconnect()`, meaning there are abandoned connection threads. This can become an issue at scale after enough calls. Please create a `disconnect()` function.

**Comment by john-osullivan** [comment]
So I just talked this over a little bit with Juan and did 15min of research, but I'm not sure if disconnecting is our responsibility.  Particularly given that we're using an HTTPProvider (not a WebSocket provider, which expects an ongoing connection), each request shouldn't create a long-term connection.

This really might be an issue with my nomenclature.  `connect()` generates the `GenericETHConnector` class and attaches it to the `Controller`, where it then powers the specific methods.  We do need some runtime init because `Controller` needs to find the network ID and pass it to the `Connector`, but `connect` might be a confusing name for it.  Maybe `detect()`?

This is definitely worth thinking through, because if we wanted to upgrade this lib to support WebSocket providers, then managing long-standing connections is a key part of the problem.

Here are the issues I found guiding my thinking:
[https://github.com/ethereum/web3.js/issues/243](https://github.com/ethereum/web3.js/issues/243)
[Handle web socket disconnects #1354](https://github.com/ethereum/web3.js/issues/1354)

What do you think, @eximchain137 ?  Check out that HTTPProvider issue -- unless I'm misunderstanding somethin, we might be able to close this.

**Comment by john-osullivan** [comment]
@fcolon @eximchain137 

As long as we continue using the HTTPProvider, I don't believe we need to manually manage those connection threads.  For the sake of reducing confusion, though, I think the `connect()` method should be renamed.  What's actually happening there is finding the `networkId`.  

Two potential replacements names are `detect()` and `identify()`.  I kind of like `identify()`, as we're looking for an identity.  Unless somebody drops in a comment saying otherwise, I'm going to rename to `identify()` during some downtime next week -- will close this issue once I've got a resolving commit.

**Comment by john-osullivan** [comment]
Renamed the method to `detectNetwork()` in [this commit](https://github.com/Eximchain/abi2lib/commit/bdc01ab1d06e45fd06b8188b900d503fb8582732), decided to err on the explicit side.  Also explicitly said it's async in the README to prevent future confusion!  Closing this out, the naming change should clarify things.
